import type { PaymentType } from "@/components/Columns";
import {
  CalendarIcon,
  HomeIcon,
  InboxIcon,
  SearchIcon,
  SettingsIcon,
} from "lucide-react";

export const SIDEBAR_ITEMS = [
  {
    title: "Home",
    url: "/",
    icon: HomeIcon,
  },
  {
    title: "Inbox",
    url: "#",
    icon: InboxIcon,
  },
  {
    title: "Calendar",
    url: "#",
    icon: CalendarIcon,
  },
  {
    title: "Search",
    url: "#",
    icon: SearchIcon,
  },
  {
    title: "Settings",
    url: "#",
    icon: SettingsIcon,
  },
];

export const IMAGES_URL = [
  "https://picsum.photos/id/1011/600/400",
  "https://picsum.photos/id/1015/600/400",
  "https://picsum.photos/id/1016/600/400",
  "https://picsum.photos/id/1020/600/400",
  "https://picsum.photos/id/1024/600/400",
  "https://picsum.photos/id/1025/600/400",
  "https://picsum.photos/id/1035/600/400",
  "https://picsum.photos/id/1039/600/400",
  "https://picsum.photos/id/1040/600/400",
  "https://picsum.photos/id/1041/600/400",
  "https://picsum.photos/id/1043/600/400",
  "https://picsum.photos/id/1050/600/400",
  "https://picsum.photos/id/1060/600/400",
  "https://picsum.photos/id/1069/600/400",
  "https://picsum.photos/id/1074/600/400",
];

export const POPULATE_CONTENTS = [
  {
    id: 1,
    title: "Mountain View",
    badge: "New",
    image: "https://picsum.photos/id/1011/600/400",
    count: 12,
  },
  {
    id: 2,
    title: "Forest Path",
    badge: "Trending",
    image: "https://picsum.photos/id/1015/600/400",
    count: 8,
  },
  {
    id: 3,
    title: "City Skyline",
    badge: "Popular",
    image: "https://picsum.photos/id/1016/600/400",
    count: 15,
  },
  {
    id: 4,
    title: "Desert Road",
    badge: "Sale",
    image: "https://picsum.photos/id/1020/600/400",
    count: 5,
  },
  {
    id: 5,
    title: "Beach Sunset",
    badge: "Hot",
    image: "https://picsum.photos/id/1024/600/400",
    count: 20,
  },
];

export const LATEST_TRANSACTIONS = [
  {
    id: 1,
    title: "Nature Landscape",
    badge: "Featured",
    image: "https://picsum.photos/id/1025/600/400",
    count: 9,
  },
  {
    id: 2,
    title: "Snow Mountains",
    badge: "New",
    image: "https://picsum.photos/id/1035/600/400",
    count: 14,
  },
  {
    id: 3,
    title: "Bridge View",
    badge: "Trending",
    image: "https://picsum.photos/id/1039/600/400",
    count: 6,
  },
  {
    id: 4,
    title: "Ocean Waves",
    badge: "Popular",
    image: "https://picsum.photos/id/1040/600/400",
    count: 11,
  },
  {
    id: 5,
    title: "Green Hills",
    badge: "Sale",
    image: "https://picsum.photos/id/1041/600/400",
    count: 7,
  },
];

export const DESCRIPTIONS = [
  { id: 1, description: "A beautiful scenic view perfect for nature lovers." },
  { id: 2, description: "High-quality product designed for everyday use." },
  { id: 3, description: "Modern and stylish design with premium finish." },
  { id: 4, description: "Lightweight, durable, and easy to carry anywhere." },
  { id: 5, description: "Crafted with attention to detail and comfort." },
  { id: 6, description: "Ideal choice for both beginners and professionals." },
  {
    id: 7,
    description: "Engineered for performance and long-lasting reliability.",
  },
  {
    id: 8,
    description: "A versatile item that fits perfectly into your lifestyle.",
  },
  { id: 9, description: "Minimalist design with maximum functionality." },
  {
    id: 10,
    description: "Built using high-grade materials for extra durability.",
  },
  { id: 11, description: "Compact size with powerful features included." },
  { id: 12, description: "A smart solution for modern-day needs." },
  { id: 13, description: "Experience comfort and elegance in one package." },
  { id: 14, description: "Perfect balance between style and performance." },
  {
    id: 15,
    description: "Designed to deliver exceptional results every time.",
  },
  { id: 16, description: "Premium quality with an affordable price tag." },
  { id: 17, description: "Simple yet powerful design for everyday tasks." },
  { id: 18, description: "Reliable and efficient for long-term usage." },
  { id: 19, description: "An innovative product built for convenience." },
  { id: 20, description: "Carefully tested to ensure top-notch quality." },
  { id: 21, description: "A perfect companion for travel and outdoor use." },
  { id: 22, description: "Combines technology and design seamlessly." },
  { id: 23, description: "Made to enhance your productivity and comfort." },
  { id: 24, description: "Sleek appearance with powerful capabilities." },
  { id: 25, description: "Trusted choice for quality and performance." },
];

export const USER_DATA: PaymentType[] = [
  {
    id: 1,
    amount: 250.75,
    status: "completed",
    email: "john.doe@example.com",
    username: "johndoe",
  },
  {
    id: 2,
    amount: 120.0,
    status: "pending",
    email: "sarah.smith@example.com",
    username: "sarahsmith",
  },
  {
    id: 3,
    amount: 560.4,
    status: "failed",
    email: "mike.johnson@example.com",
    username: "mikej",
  },
  {
    id: 4,
    amount: 89.99,
    status: "completed",
    email: "emma.wilson@example.com",
    username: "emmaw",
  },
  {
    id: 5,
    amount: 310.2,
    status: "pending",
    email: "alex.brown@example.com",
    username: "alexb",
  },
  {
    id: 6,
    amount: 45.5,
    status: "completed",
    email: "olivia.taylor@example.com",
    username: "oliviat",
  },
  {
    id: 7,
    amount: 780.0,
    status: "failed",
    email: "liam.anderson@example.com",
    username: "liama",
  },
  {
    id: 8,
    amount: 199.99,
    status: "pending",
    email: "noah.thomas@example.com",
    username: "noaht",
  },
  {
    id: 9,
    amount: 650.3,
    status: "completed",
    email: "ava.jackson@example.com",
    username: "avaj",
  },
  {
    id: 10,
    amount: 72.1,
    status: "failed",
    email: "william.white@example.com",
    username: "willw",
  },
  {
    id: 11,
    amount: 430.0,
    status: "completed",
    email: "sophia.harris@example.com",
    username: "sophiah",
  },
  {
    id: 12,
    amount: 215.75,
    status: "pending",
    email: "james.martin@example.com",
    username: "jamesm",
  },
  {
    id: 13,
    amount: 999.99,
    status: "completed",
    email: "isabella.clark@example.com",
    username: "isabellac",
  },
  {
    id: 14,
    amount: 134.6,
    status: "failed",
    email: "benjamin.lewis@example.com",
    username: "benl",
  },
  {
    id: 15,
    amount: 58.4,
    status: "pending",
    email: "mia.walker@example.com",
    username: "miaw",
  },
  {
    id: 16,
    amount: 820.15,
    status: "completed",
    email: "lucas.hall@example.com",
    username: "lucash",
  },
  {
    id: 17,
    amount: 300.0,
    status: "failed",
    email: "charlotte.allen@example.com",
    username: "charlottea",
  },
  {
    id: 18,
    amount: 410.85,
    status: "completed",
    email: "henry.young@example.com",
    username: "henryy",
  },
  {
    id: 19,
    amount: 275.25,
    status: "pending",
    email: "amelia.king@example.com",
    username: "ameliak",
  },
  {
    id: 20,
    amount: 150.9,
    status: "completed",
    email: "daniel.scott@example.com",
    username: "daniels",
  },
];
